### ISSUE TITLE
collect_data_autopilot gives error 'Carla_session' object has no attribute 'vehicle'

### ISSUE THREAD

**Issue by shivamakhauri04** [perseus784/Vehicle_Collision_Prediction_Using_CNN-LSTMs#2]
Hello
Thanks for the great repo. Wanted to inquire that the data generation code throws an error as described above. When I run spwan_npc.py in the background and run your code in parallel, the error type changes to spawning collisions.

**Comment by perseus784** [comment]
Hey,
So, the default code provided by Carla is written in a different way. The code present in this repo is custom. So, it may cause conflicts while running them simultaneously. So, one has to be careful while running them parallelly. The underlying problem would be because of same spawn points since I am using some of the spawn points, those might not be available for the spawn_npc.py program. 

I would suggest you to either modify the code in this repo or use the default python code by the Carla. Hope this clarifies.

**Comment by shivamakhauri04** [comment]
Thanks for the reply. 
Running your collect_data_autopilot.py without running spawn_npc.py in parallel throws the error "Carla_session' object has no attribute 'vehicle'. Any idea why is that happening?

Regards

**Comment by perseus784** [comment]
Oh, Yes. That might be an issue with Carla not being imported. So, in order to make Carla universal, I put the Carla egg file in the python library directory. This makes the Carla universal and you can import Carla anywhere in your system. Else the Carla only works when inside the specified folder in the Python API. 
To check if we are at the same page, try to import carla in your python ide. If it doesn't work then that is the problem.
You can do the following, either insert the carla egg import lines in the spwan_npc.py program in your program ( with file path changes to navigate to the egg file) or you can put your carla egg file inside the python library. Follow this: http://peak.telecommunity.com/DevCenter/PythonEggs or https://stackoverflow.com/questions/18558733/how-can-i-install-a-egg-python-package-on-windows-attempt-using-easy-install-n

**Comment by shivamakhauri04** [comment]
Thanks for your reply. I think the issue is something else. I am running in Linux and I have made sure that Carla is imported in the python library. As when I run python I am able to import Carla from anywhere. The error says 'no attribute vehicle'

**Comment by perseus784** [comment]
Can you do the same in the python interpreter?, Try importing the vehicle in the interpreter. And can you provide the code in which lines you are facing the issue with the error message?, It most probably has to do with carla.

**Comment by shivamakhauri04** [comment]
![Screenshot from 2020-06-05 15-45-15](https://user-images.githubusercontent.com/29355854/83916705-a3bde500-a743-11ea-825d-cbac2cd687a2.png)

**Comment by shivamakhauri04** [comment]
The above is the error I get

**Comment by perseus784** [comment]
Okay, there is some error with starting a new sequence. Can you print the try exception error and see what is causing it? Line 138, it is bad coding practice from my part I pass the error silently. But it might be an error that you got but I didn't get.
